# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2
# SPHINX SETTINGS
sphinx:
  configuration: docs/source/conf.py
# BUILD FORMATS
formats: all


python:
  version: 3.7
  install:
    - method: setuptools
      path: .
